/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "auth.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(auth_AuthInitRequest, auth_AuthInitRequest, AUTO)


PB_BIND(auth_AuthInitResponse, auth_AuthInitResponse, AUTO)


PB_BIND(auth_Challenge, auth_Challenge, AUTO)


PB_BIND(auth_ChallengeResponse, auth_ChallengeResponse, AUTO)



