/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_AUTH_AUTH_PB_H_INCLUDED
#define PB_AUTH_AUTH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Step 1: Client → Server
 - serial_id: client ka ID (string as bytes)
 - signature: ECDSA signature over SHA256(serial_id)
 - client_pubkey: 65-byte uncompressed ECDSA pubkey (secp256k1) */
typedef struct _auth_AuthInitRequest {
    pb_callback_t serial_id;
    pb_callback_t signature;
    pb_callback_t client_pubkey;
} auth_AuthInitRequest;

/* Step 2: Server → Client
 - ok: true if initial signature verified
 - error_msg: optional human-readable error */
typedef struct _auth_AuthInitResponse {
    bool ok;
    pb_callback_t error_msg;
} auth_AuthInitResponse;

/* Step 3: Server → Client
 - nonce: 32-byte random challenge */
typedef struct _auth_Challenge {
    pb_callback_t nonce;
} auth_Challenge;

/* Step 4: Client → Server
 - serial_id: same serial id
 - signature: ECDSA signature over SHA256(nonce) */
typedef struct _auth_ChallengeResponse {
    pb_callback_t serial_id;
    pb_callback_t signature;
} auth_ChallengeResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define auth_AuthInitRequest_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define auth_AuthInitResponse_init_default       {0, {{NULL}, NULL}}
#define auth_Challenge_init_default              {{{NULL}, NULL}}
#define auth_ChallengeResponse_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define auth_AuthInitRequest_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define auth_AuthInitResponse_init_zero          {0, {{NULL}, NULL}}
#define auth_Challenge_init_zero                 {{{NULL}, NULL}}
#define auth_ChallengeResponse_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define auth_AuthInitRequest_serial_id_tag       1
#define auth_AuthInitRequest_signature_tag       2
#define auth_AuthInitRequest_client_pubkey_tag   3
#define auth_AuthInitResponse_ok_tag             1
#define auth_AuthInitResponse_error_msg_tag      2
#define auth_Challenge_nonce_tag                 1
#define auth_ChallengeResponse_serial_id_tag     1
#define auth_ChallengeResponse_signature_tag     2

/* Struct field encoding specification for nanopb */
#define auth_AuthInitRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    serial_id,         1) \
X(a, CALLBACK, REQUIRED, BYTES,    signature,         2) \
X(a, CALLBACK, REQUIRED, BYTES,    client_pubkey,     3)
#define auth_AuthInitRequest_CALLBACK pb_default_field_callback
#define auth_AuthInitRequest_DEFAULT NULL

#define auth_AuthInitResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     ok,                1) \
X(a, CALLBACK, OPTIONAL, STRING,   error_msg,         2)
#define auth_AuthInitResponse_CALLBACK pb_default_field_callback
#define auth_AuthInitResponse_DEFAULT NULL

#define auth_Challenge_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    nonce,             1)
#define auth_Challenge_CALLBACK pb_default_field_callback
#define auth_Challenge_DEFAULT NULL

#define auth_ChallengeResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    serial_id,         1) \
X(a, CALLBACK, REQUIRED, BYTES,    signature,         2)
#define auth_ChallengeResponse_CALLBACK pb_default_field_callback
#define auth_ChallengeResponse_DEFAULT NULL

extern const pb_msgdesc_t auth_AuthInitRequest_msg;
extern const pb_msgdesc_t auth_AuthInitResponse_msg;
extern const pb_msgdesc_t auth_Challenge_msg;
extern const pb_msgdesc_t auth_ChallengeResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define auth_AuthInitRequest_fields &auth_AuthInitRequest_msg
#define auth_AuthInitResponse_fields &auth_AuthInitResponse_msg
#define auth_Challenge_fields &auth_Challenge_msg
#define auth_ChallengeResponse_fields &auth_ChallengeResponse_msg

/* Maximum encoded size of messages (where known) */
/* auth_AuthInitRequest_size depends on runtime parameters */
/* auth_AuthInitResponse_size depends on runtime parameters */
/* auth_Challenge_size depends on runtime parameters */
/* auth_ChallengeResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
